###
GET http://localhost:3000/usuarios HTTP/1.1
###

POST http://localhost:3000/usuarios
content-Type: application/json

    {
        "id": 3,
        "name" : "ivan sebastian",
        "lastname": "almeida valencia",
        "phone": "3124589636",
        "email" : "sebas@hotmail.com",
        "sex": "M"
    }

###
PUT http://localhost:3000/usuarios/2 HTTP/1.1
content-Type: application/json

    {
        "name" : "casimiro tibursio",
        "lastname": "palacios casaosos",
        "phone": "3124589636",
        "email" : "tiburcio@hotmail.com",
        "sex": "M"
    }

###

DELETE http://localhost:3000/usuarios/3 HTTP/1.1